USE AMAZON

DROP TABLE EMP

CREATE TABLE EMP(ID INT,NAME CHAR(10),SALARY MONEY)
SELECT *FROM EMP

INSERT INTO EMP VALUES(1,'HR',1000)
INSERT INTO EMP VALUES(2,'MANAGER',2000)
INSERT INTO EMP VALUES(3,'TL',3000)
INSERT INTO EMP VALUES(4,'HR',4000)
INSERT INTO EMP VALUES(5,'TL',5000)
INSERT INTO EMP VALUES(6,'MANAGER',6000)
INSERT INTO EMP VALUES(7,'HR',1200)
INSERT INTO EMP VALUES(8,'TL',1400)

/*GROUP BY CLAUSES*/


SELECT NAME, COUNT(*) AS COUNT_VALUE FROM EMP GROUP BY NAME

SELECT NAME, COUNT(*) AS VALUE, SUM(SALARY) AS TOTAL FROM EMP GROUP BY NAME

SELECT NAME, COUNT(*) AS VALUE, SUM(SALARY) AS TOTAL, AVG(SALARY) AS AVG FROM EMP GROUP BY NAME

/*HAVING CLAUSES*/

SELECT NAME, COUNT(*) AS VALUE FROM EMP GROUP BY NAME HAVING COUNT(*)>2

SELECT NAME, COUNT(*) AS VALUE, SUM(SALARY) AS TOTAL FROM EMP GROUP BY NAME HAVING SUM(SALARY)>7000

SELECT NAME, COUNT(*) AS VALUE, SUM(SALARY) AS TOTAL, AVG(SALARY) AS AVG FROM EMP GROUP BY NAME HAVING AVG(SALARY)>3000
