use amazon
SELECT * FROM COLLEGE
SELECT * FROM SCHOOL
SELECT  SID,SNAME FROM COLLEGE
TRUNCATE TABLE SCHOOL

CREATE TABLE SCHOOL(ID INT, NAME CHAR(10),AGE INT)
CREATE TABLE COLLEGE(ID INT, NAME CHAR(10),AGE INT)


INSERT INTO SCHOOL VALUES(12,'PPP',98),(2,'LLL',89),(14,'MMM',54),(4,'JJJ',65)
INSERT INTO COLLEGE VALUES(13,'POP',88),(2,'LOL',90),(18,'MOM',58),(4,'JOJ',75)



SELECT *FROM COLLEGE INNER JOIN SCHOOL ON COLLEGE.ID=SCHOOL.ID

SELECT *FROM COLLEGE LEFT OUTER JOIN SCHOOL ON COLLEGE.ID=SCHOOL.ID

SELECT *FROM COLLEGE RIGHT JOIN SCHOOL ON COLLEGE.ID=SCHOOL.ID

SELECT *FROM COLLEGE FULL OUTER JOIN SCHOOL ON COLLEGE.ID=SCHOOL.ID


SELECT * FROM COLLEGE CROSS JOIN SCHOOL


SELECT *FROM COLLEGE , SCHOOL WHERE COLLEGE.ID=SCHOOL.ID

SELECT *FROM COLLEGE , SCHOOL WHERE COLLEGE.ID>SCHOOL.ID

