USE AMAZON

CREATE TABLE SCHOOL(STDID INT IDENTITY, STDNAME CHAR(10), STDAGE TINYINT)
SELECT * FROM SCHOOL

INSERT INTO SCHOOL VALUES('LAL',5)
INSERT INTO SCHOOL VALUES('LAL',5)
INSERT INTO SCHOOL VALUES('LAL',5)
INSERT INTO SCHOOL VALUES('LAL',5)


CREATE TABLE COLLEGE(STDID INT IDENTITY(10,1), STDNAME CHAR(10), STDAGE TINYINT)
SELECT * FROM SCHOOL

INSERT INTO COLLEGE VALUES('LAL',5)
INSERT INTO COLLEGE VALUES('LAL',5)
INSERT INTO COLLEGE VALUES('JAL',6)
INSERT INTO COLLEGE VALUES('RAL',8)
SELECT * FROM COLLEGE






