USE AMAZON

CREATE TABLE TEACHER(ID INT PRIMARY KEY,NAMR CHAR(10), AGE INT)
CREATE TABLE STUDENT(NAMR CHAR(10), AGE INT,ID INT FOREIGN KEY REFERENCES TEACHER(ID) ON UPDATE CASCADE  ON DELETE CASCADE)

SELECT * FROM TEACHER
SELECT * FROM STUDENT

INSERT INTO TEACHER VALUES(1,'PPP',11)
INSERT INTO TEACHER VALUES(2,'OOO',12)
INSERT INTO TEACHER VALUES(3,'III',13)
INSERT INTO TEACHER VALUES(4,'UUU',14)
INSERT INTO TEACHER VALUES(5,'UHU',16)


INSERT INTO STUDENT VALUES('LLL',15,1)
INSERT INTO STUDENT VALUES('KKK',16,2)
INSERT INTO STUDENT VALUES('JJJ',17,3)
INSERT INTO STUDENT VALUES('HHH',18,4)

INSERT INTO STUDENT VALUES('YYY',19,5)


UPDATE TEACHER SET NAMR='POP' WHERE NAMR='UUU'
UPDATE TEACHER SET AGE=10 WHERE AGE=11
UPDATE TEACHER SET ID=30 WHERE ID=3

DELETE TEACHER WHERE ID=1

UPDATE STUDENT SET AGE =55 WHERE AGE=19

UPDATE STUDENT SET ID =10 WHERE ID=5

DROP TABLE TEACHER
DROP TABLE STUDENT

CREATE TABLE TEACHER(ID INT PRIMARY KEY,N CHAR(10), AGE INT)
CREATE TABLE STUDENT(N CHAR(10),AGE INT , ID INT FOREIGN KEY REFERENCES TEACHER(ID))

SELECT *FROM TEACHER
SELECT *FROM STUDENT

INSERT INTO TEACHER VALUES(1,'PPP',11)
INSERT INTO TEACHER VALUES(2,'OOO',12)
INSERT INTO TEACHER VALUES(3,'III',13)
INSERT INTO TEACHER VALUES(4,'UUU',14)
INSERT INTO TEACHER VALUES(5,'UHU',16)

INSERT INTO STUDENT VALUES('LLL',15,1)
INSERT INTO STUDENT VALUES('KKK',16,2)
INSERT INTO STUDENT VALUES('JJJ',17,3)
INSERT INTO STUDENT VALUES('HHH',18,4)
INSERT INTO STUDENT VALUES('YYY',19,5) 

INSERT INTO TEACHER VALUES(6,'LLM',79)

DELETE TEACHER WHERE ID=6

INSERT INTO STUDENT VALUES ('PPO',89,6) /* HERE ERROR */

DELETE STUDENT WHERE ID=5  /* WE CAN DELETE ANYTHING IN CHILD TABLE */

SELECT *FROM TEACHER
SELECT *FROM STUDENT

UPDATE TEACHER SET ID=10 WHERE ID=1 /* WE CAN'T UPDATE REFERENCED COLUMN */

UPDATE TEACHER SET ID=50 WHERE ID=5 /* WE CAN UPDATE THIS BCZ ROW IS NOT REFERED */

DELETE TEACHER WHERE ID=4 /* ERROR CAN'T DELETE THE REFERENCE COLUMN*/

INSERT INTO STUDENT VALUES('PLM',90,50)

UPDATE STUDENT SET ID=5 WHERE ID=50

UPDATE TEACHER SET ID=5 WHERE ID=50

INSERT INTO STUDENT VALUES('PLM',90,6) /* ERROR BCZ REFERED COLUMN NOT THERE IN PARENT TABLE */

INSERT INTO TEACHER VALUES(6,'TTT',76)

UPDATE TEACHER SET ID=60 WHERE ID=6
