USE AMAZON

CREATE TABLE EMP(ID INT,NAME CHAR(10),SALARY INT)

SELECT *FROM EMP

/*ROW WISE RANKING */

INSERT INTO EMP VALUES (1,'PPP',1000)
INSERT INTO EMP VALUES (2,'AAA',2000)
INSERT INTO EMP VALUES (3,'WWW',1000)
INSERT INTO EMP VALUES (4,'EEE',3000)
INSERT INTO EMP VALUES (5,'TTT',4000)

SELECT ID,NAME,SALARY,ROW_NUMBER() OVER (ORDER BY SALARY ASC) AS LADDU FROM EMP

SELECT ID,NAME,SALARY,RANK() OVER (ORDER BY SALARY ASC) AS LADDU FROM EMP

SELECT ID,NAME,SALARY,DENSE_RANK() OVER (ORDER BY SALARY ASC) AS LADDU FROM EMP

 TRUNCATE TABLE EMP

 /* GROUP WISE RANKING*/

INSERT INTO EMP VALUES (1,'PPP',1000)
INSERT INTO EMP VALUES (1,'AAA',2000)
INSERT INTO EMP VALUES (1,'WWW',1000)
INSERT INTO EMP VALUES (1,'EEE',3000)
INSERT INTO EMP VALUES (1,'TTT',4000)

INSERT INTO EMP VALUES (2,'PPP',1000)
INSERT INTO EMP VALUES (2,'AAA',2000)
INSERT INTO EMP VALUES (2,'WWW',1000)
INSERT INTO EMP VALUES (2,'EEE',3000)
INSERT INTO EMP VALUES (2,'TTT',4000)

INSERT INTO EMP VALUES (3,'EEE',3000)
INSERT INTO EMP VALUES (3,'TTT',4000)

SELECT *FROM EMP

SELECT ID,NAME,SALARY,ROW_NUMBER() OVER (PARTITION BY ID ORDER BY SALARY ASC) AS LADDU FROM EMP

SELECT ID,NAME,SALARY,RANK() OVER (PARTITION BY ID ORDER BY SALARY ASC) AS LADDU FROM EMP

SELECT ID,NAME,SALARY,DENSE_RANK() OVER (PARTITION BY ID ORDER BY SALARY DESC) AS LADDU FROM EMP
