USE AMAZON
CREATE TABLE SCHOOL(SID INT,SNAME CHAR(10), SAGE TINYINT)
CREATE TABLE COLLEGE(SID INT,SNAME CHAR(10), SAGE TINYINT)

SELECT * FROM SCHOOL
SELECT * FROM COLLEGE

INSERT INTO SCHOOL VALUES(1,'LAL',33)
INSERT INTO SCHOOL VALUES(2,'RAL',39)
INSERT INTO SCHOOL VALUES(3,'JAL',33)
INSERT INTO SCHOOL VALUES(4,'PAL',31)

INSERT INTO COLLEGE VALUES(1,'MAL',33)
INSERT INTO COLLEGE VALUES(2,'OAL',39)
INSERT INTO COLLEGE VALUES(3,'JAL',33)
INSERT INTO COLLEGE VALUES(4,'PAL',31)

SELECT * FROM SCHOOL
UNION
SELECT * FROM COLLEGE

SELECT * FROM SCHOOL
UNION ALL
SELECT * FROM COLLEGE

SELECT * FROM SCHOOL
INTERSECT
SELECT * FROM COLLEGE

SELECT * FROM SCHOOL
EXCEPT
SELECT * FROM COLLEGE
