/* Creating my own DB */

CREATE DATABASE AMAZON


/* ACTIVATE DATABASE */
USE AMAZON

CREATE TABLE EMPLOY (EMPID INT, EMPNAME VARCHAR(10), EMPSAL INT, EMPAGE INT)

SELECT * FROM EMPLOY

ALTER TABLE EMPLOY ALTER COLUMN EMPAGE TINYINT
ALTER TABLE EMPLOY ADD EMPPIN INT
ALTER TABLE EMPLOY DROP COLUMN EMPPIN

SP_RENAME 'EMPLOY.EMPSAL','EMPSALARY'

INSERT INTO EMPLOY VALUES (1,'RAM',1000,22)
INSERT INTO EMPLOY VALUES (2,'ALA',2000,23)
INSERT INTO EMPLOY VALUES (3,'EAL',3000,24)
INSERT INTO EMPLOY VALUES (4,'LAL',4000,25)

SELECT * FROM EMPLOY

UPDATE EMPLOY SET EMPSALARY=9000 WHERE EMPID=4
UPDATE EMPLOY SET EMPAGE=30 WHERE EMPAGE=22

DELETE EMPLOY WHERE EMPID=1

DELETE EMPLOY

INSERT INTO EMPLOY VALUES (1,'RAM',1000,22)
INSERT INTO EMPLOY VALUES (2,'ALA',2000,23)
INSERT INTO EMPLOY VALUES (3,'EAL',3000,24)
INSERT INTO EMPLOY VALUES (4,'LAL',4000,25)

SELECT * FROM EMPLOY


TRUNCATE TABLE EMPLOY

DROP TABLE EMPLOY