USE AMAZON
CREATE TABLE EMP(ID INT, NAME CHAR(10),SALARY MONEY)

SELECT * FROM EMP

BEGIN TRANSACTION
INSERT INTO EMP VALUES(1,'PPP',1000)
INSERT INTO EMP VALUES(2,'QQP',1200)
COMMIT

BEGIN TRANSACTION
ROLLBACK

BEGIN TRANSACTION
INSERT INTO EMP VALUES(3,'LLL',2000)

BEGIN TRANSACTION
UPDATE EMP SET ID=20 WHERE ID=2
COMMIT

BEGIN TRANSACTION
UPDATE EMP SET SALARY=20 WHERE NAME='POP'
TRUNCATE TABLE EMP